### ISSUE TITLE
Incorrect URL Duplicate info

### ISSUE THREAD

**Issue by Targox** [StJudeWasHere/seonaut#1]
I have these alerts: 2 URLs Duplicate description and 2 URLs duplicate title, but they are about the same url.

<img width="1631" alt="Screenshot 2022-04-23 at 15 17 57" src="https://user-images.githubusercontent.com/949130/164896231-176de1fa-87b4-4938-876c-1803c54bb414.png">

**Comment by StJudeWasHere** [comment]
This should be fixed now and your next crawl will report it correctly. Thanks for reporting!
