### ISSUE TITLE
Lock signups

### ISSUE THREAD

**Issue by Entretoize** [StJudeWasHere/seonaut#10]
I installed it on my web server that is available publicly, but I'm worrying about security, first it is http then everybody can sign up and use it !
Can I protect the access to it without having to install a proxy ? Is there php files I can change somewhere to prevent signups ?

**Comment by StJudeWasHere** [comment]
There are no plans to add this features at this point, so I suggest using a reverse proxy like Nginx as advised in the documentation, that way you can configure it to use HTTPS and add HTTP Auth if needed.

I'm closing this issue but I'll be happy to review any pull request that includes any of the requested features.
