### ISSUE TITLE
robots.txt and sitemap.xml not found when using basic auth

### ISSUE THREAD

**Issue by klaus-aunds** [StJudeWasHere/seonaut#11]
**Describe the bug**
When basic auth is active, seonaut fails to find the sitemap and robots.txt.

**To Reproduce**
1. generate a simple file structure to serve: `index.html`, `robots.txt`, `sitemap.xml` in a directory
2. create a vhost to serve the test directory. Do not use basic auth
3. run seonaut against the test vhost
4. check that `robots.txt` and `sitemap.xml` were found
5. edit the vhost and put everything under `/` behind basic auth
6. run seonaut again
7. check that `robots.txt` and `sitemap.xml` were not found

**Expected behavior**
Both files are found regardless of basic auth

**Sample vhost directory content**

`index.html`
```
hi
```

`sitemap.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

  <url>
    <loc>http://example.com/</loc>
    <lastmod>2023-10-04</lastmod>
    <changefreq>monthly</changefreq>
  </url>

  <url>
    <loc>http://example.com/nope</loc>
    <lastmod>2023-10-04</lastmod>
    <changefreq>monthly</changefreq>
  </url>

</urlset>
```

`robots.txt`
```
User-agent: *
Allow: /

Sitemap: http://example.com/sitemap.xml
```

**Comment by StJudeWasHere** [comment]
This is fixed now, thanks for reporting.
