### ISSUE TITLE
False positive alert : Mismatching language

### ISSUE THREAD

**Issue by BrangGit** [StJudeWasHere/seonaut#13]
**Describe the bug**
Got a "Mismatching language" alert for pages that have the following meta tags :
_URL_ : https://example.com/fr/contact/
_Canonical_ : https://example.com/fr/contact/
_Language_ : fr
_Hreflang_ : 
fr https://example.com/fr/contact/
en https://example.com/en/contact/
x-default https://example.com/fr/contact/

**To Reproduce**
1. Set up meta tags for a multilingual site as in the exemple
2. Crawl site on SEOnaut
3. Go to site issues
4. See error "Mismatching language"

**Expected behavior**
I shouldn't get the "Mismatching language" alert since the meta tags are properly set

**Comment by StJudeWasHere** [comment]
This should be fixed now in commit c566ea2.

Thanks for reporting the issue.
