### ISSUE TITLE
Podman Launch Error: `glibc error: CPU does not support x86-64-v2`

### ISSUE THREAD

**Issue by anoduck** [StJudeWasHere/seonaut#16]
**Describe the bug**

This bug report is more of a "Heads up" than anything else.  

Getting seonaut to run on podman took some finagling. All that was needed was adding `docker.io/` to the image designators, and adding the ports for mysql to the compose file.

The error is the result of the Mysql container requiring AVX support, which the system did not have. 

After reviewing the documentation for `go-sql-driver/mysql` I exchanged mysql with mariadb, which does not require AVX. ~~The problem is that although mariadb is up, seonaut still does not recognize that it is up. Which is what I am working on at this moment.~~

----

Designating IP addresses, hostnames, and adding `extra_hosts` entries to the `docker-compose.yml` file allowed docker-compose-wait to successfully recognize when the database client has become available. This has allowed seonaut to run and be accessible on localhost, but for some reason, podman is not allowing external access right now. Which is something to work out at a later time.

**Comment by StJudeWasHere** [comment]
Thanks for the heads-up!

I don't use Podman myself, and so far, I don't have any plans to add support for it. However, feel free to make a PR if the needed changes do not break the current Docker environment.

**Comment by anoduck** [comment]
@StJudeWasHere Honestly, what you have done is so awesome, I wouldn't want to make any part of it even an iota more difficult. 

I am having buyer's remorse for making the move to podman. It claims to be a drop-in replacement for docker, but it is not.

The only real modification needed to circumvent reception of the error is exchanging MySQL for MariaDB. MySQL requires AVX now, MariaDB does not. Same SQL syntax, just a different DB engine. 

The decision is your preference. In my situation, if it doesn't work on my old box, I will just have to pull my britches up and find another box around here.
