### ISSUE TITLE
crawler crash on old amazon widget

### ISSUE THREAD

**Issue by JonathanMH** [StJudeWasHere/seonaut#19]
First of all, this is a very cool repo, I do some GO web crawling as well, but not as elaborate or complete as this wonderful project :raised_hands: 

**Describe the bug**
I tried out seonaut to crawl one of my blogs and it had an ancient (and dysfunctional) amazon affiliate widget that caused the crawler to crash.

**To Reproduce**
1. place the below code onto a page to be crawled
2. start the crawler to have it discover it

(the HTML version, original is markdown)
```
<a href="https://www.amazon.com/gp/product/0321966465/ref=as_li_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0321966465&amp;linkCode=as2&amp;tag=redacted-30-01&amp;linkId=21e9a7acc8b074669293181be87b0bb1">
  <img src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&amp;MarketPlace=US&amp;ASIN=0321966465&amp;ServiceVersion=20070822&amp;ID=AsinImage&amp;WS=1&amp;Format=_SL250_&amp;tag=redacted-30-01" alt="" loading="lazy">
</a>
```

**Expected behavior**
It should flag both link and image link as a regular error, but instead it crashes the currently running crawl:

```
SEOnaut-app  | 2024/08/04 09:33:31 callback function error: Get "https://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=US&ASIN=0321966465&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=redacted-30-01": dial tcp: lookup ws-na.amazon-adsystem.com on 127.0.0.11:53: no such host
SEOnaut-app  | panic: runtime error: invalid memory address or nil pointer dereference 
```

**Comment by StJudeWasHere** [comment]
This should be fixed in cc7dc26.

Thanks for reporting the issue.
