### ISSUE TITLE
A button to remove a project on seonaut.org

### ISSUE THREAD

**Issue by mxcrml** [StJudeWasHere/seonaut#2]
Hi, 

Can we remove a project (or free a slot for a new website) on seonaut.org ? If not, it seems to be an priority feature for usability :) To avoid abuse, you could add a limit of maximum project change per month (that could be a metric).

Thank you :)

**Comment by StJudeWasHere** [comment]
The hosted free version at seonaut.org has some limitations to avoid abuse, but the open source version has unlimited slots for websites. 

However, I agree that we need a way to delete projects as that hasn't been implemented yet.

**Comment by StJudeWasHere** [comment]
Implemented in a3685c615caa80e45dbf316e72f29faea7a46604.
