### ISSUE TITLE
Error connecting to WebSocket

### ISSUE THREAD

**Issue by andersme** [StJudeWasHere/seonaut#22]
**Describe the bug**

When going to the 'crawl-live' page for any project, there is an error connecting to WebSocket. This appears to be an issue only when the host address isn't localhost. The error we see is this:

WebSocket connection to 'ws://XXX.XXX.X.XXX:9000/crawl-ws?pid=1' failed

**To Reproduce**

1. Run an instance of SEOnaut on any host other than localhost
2. Go to '/crawl-live' for any project
3. See that the connection to the server is never established

**Expected behavior**

The connection to be established and be able to monitor a crawl.

**Comment by StJudeWasHere** [comment]
You must set your domain name in the config file for it to work.
