### ISSUE TITLE
URL Splitting Generates Numerous False Positives

### ISSUE THREAD

**Issue by anoduck** [StJudeWasHere/seonaut#23]
**Describe the bug**

Scraped my new site and received a massive amount of false positive "404" issues. It turns out Seonaut's crawler is splitting Cloudinary URLs, because they include commas in them. I imagine it reproduces similar results for any URL that includes commas. 

Take this block of HTML for example:

```html
<img class=img-fluid src=[https://res.cloudinary.com/demo/image/upload/c_fill,h_2800,w_2800//dog.png](view-source:https://res.cloudinary.com/demo/image/upload/c_fill,h_2800,w_2800//dog.png)
srcset="https://res.cloudinary.com/demo/image/upload/f_auto,c_fill,h_576,w_576//dog.webp 576w,
https://res.cloudinary.com/demo/image/upload/f_auto,c_fill,h_768,w_768//dog.webp 768w,
https://res.cloudinary.com/demo/image/upload/f_auto,c_fill,h_992,w_992//dog.webp 992w,
https://res.cloudinary.com/demo/image/upload/f_auto,c_fill,h_1200,w_1200//dog.webp 1200w,
https://res.cloudinary.com/demo/image/upload/f_auto,c_fill,h_1400,w_1400//dog.webp 1400w,
https://res.cloudinary.com/demo/image/upload/f_auto,c_fill,h_2800,w_2800//dog.webp 2800w"
sizes=100vw height=2800 width=2800 alt="Cloudinary image">
<figcaption class=figure-caption>Cloudinary image</figcaption>
```

Seonaut interprets every `f_auto`, `c_fill`, `h_XXX`, and `w_XXXX` as `$SCHEME://$HOST/$UNDERSCORED_PATTERN` or to put it simpler, `https://example.com/c_fill`. Then, when it tries to visit the misinterpreted link, and reports back a 404. 

**To Reproduce**
1. Create an empty folder and change directory into it: `mkdir test-page && cd $_`
2. Generate a boilerplate from [htmlboilerplates](https://htmlboilerplates.com/)
3. Copy and paste the boilerplate into the file `index.html`.
4. Add any of the above cloudinary image urls as an image tag to that file.
5. Launch a dev web server, `simple_web_server -p 8080`
6. Scrape that page with Seonaut

You should receive similar reports of false positive 404 issues.

**Expected behavior**
Did not expect it to split the urls.

**Comment by anoduck** [comment]
You did such an awesome job creating this masterpiece, I just wanted to make sure it stays cool. Thanks for your work.

**Comment by anoduck** [comment]
@StJudeWasHere Error still persists. I have created a test repository with a flushed out site to better replicate the error.

https://github.com/anoduck/seonaut-testsite

**Comment by StJudeWasHere** [comment]
> @StJudeWasHere Error still persists. I have created a test repository with a flushed out site to better replicate the error.
> 
> https://github.com/anoduck/seonaut-testsite

I appreciate the effort, but I don't have time to set it all up. Can you provide a simple html instead?

On the other hand, I'm not getting 404 issues anymore and URLs are not being split. I get "URLS with multiple slashes in the path" alerts instead, which is fine as the URLs actually contain multiple slashes (//).

**Comment by anoduck** [comment]
@StJudeWasHere I am trying to think of a way to make it as easy as possible. The problem is how the framework modifies urls of Digital Asset Managers. We have several options to accomplish this:

1. I can just provide my site address.
2. I can set up the site as a github site.
3. I can host it off of one of my servers. 
4. The previous mentioned test configuration should be no hassle, since the public folder containing the built site is (now) available (I forgot to include it). You can host it with live-server.


```bash
#!/usr/bin

npm install && npm run mod:update;
npm run build;
cd public && npx live-server --port=8080 --no-browser --entry-file=index.html .

```

**Comment by StJudeWasHere** [comment]
Send me your URL and I'll run a test audit on it. You can send it to the [SEOnaut.org](https://seonaut.org/support/) email address.

**Comment by anoduck** [comment]
@StJudeWasHere This one is resolved. Scraped beautifully, and Seonaut is as impressive as ever. Thank you.
