### ISSUE TITLE
Some "in-text" anchors are missing for internal links

### ISSUE THREAD

**Issue by mxcrml** [StJudeWasHere/seonaut#3]
Anchors for in-text internal links does not display correctly like it is the case for external links. I guess this is a known issues, just reporting it in case. I spend some time during my lunch digging a bit further on your tool and it is excellent. 

Congratulations again.

**Comment by StJudeWasHere** [comment]
I will need more information on this one. Any example you can provide will be appreciated.

Thanks

**Comment by mxcrml** [comment]
Well, here is an example :

For this URL _https://www.astralrank.com/referencer-son-site_ and the following anchor (in the body>content section)

> <a href="https://www.astralrank.com/">référencement naturel à Nancy</a> 

The [report](https://app.seonaut.org/resources?pid=105&rid=89964&eid=ERROR_NOT_VALID_HEADINGS&t=internal) ERROR_NOT_VALID_HEADINGS&**t=internal** for internal links do not display the anchor « référencement naturel à Nancy ». I have a feeling that some other anchors are not all well defined as well.

![Internal Links - Contact page](https://user-images.githubusercontent.com/99789620/178046808-8ec118e3-8615-47cf-ad8b-6c80590a06f1.png)

Results do look much better for external links 👍, for instance here are the results for this [blog post](https://www.astralrank.com/blog/optimisations-seo-climat-environnement) 

![External Links - blog post](https://user-images.githubusercontent.com/99789620/178047182-a67bdda2-2120-40bc-9003-3830e506a9b3.png)

Scraping the anchors and filtering them correctly would allow to include a semantic analysis of anchors after that (same applies for title, hn, metas, etc.).

Hope this is clearer :)

**Comment by StJudeWasHere** [comment]
Only a small set of the links were displayed, as pagination for links, both internal and external, hadn't been implemented yet. This has now been implemented in 8162fef39747fdb4a6d4abf14d30374cf696834b.
