### ISSUE TITLE
How to cancel a crawl?

### ISSUE THREAD

**Issue by Quin452** [StJudeWasHere/seonaut#4]
**Describe the bug**
I've started a crawl, but it's stuck on "Connecting to the server, please wait..."
I mistakenly selected HTTP auth, but there isn't any on the site.

**To Reproduce**
1. Create a new project (that **doesn't** need basic auth)
2. Select HTTP Basic Auth
3. Put in some details
4. Run, and see the error

**Expected behavior**
Either to timeout after a while, or the option to manually cancel a crawl.

**Comment by StJudeWasHere** [comment]
Cancelling a crawl is not supported yet, but it should definitively time out in this case. Thanks for reporting the issue.

**Comment by StJudeWasHere** [comment]
I'm looking into this issue but can't really reproduce it. @Quin452 more details would be needed, can you share the URL and the full crawl settings?

**Comment by StJudeWasHere** [comment]
I'm closing this issue as I haven't been able to reproduce it. In case it keeps happening, make sure you are using the latest version available and add any details that can help identify the problem. Thanks.
