### ISSUE TITLE
Integration with Github Actions

### ISSUE THREAD

**Issue by jorgemasta** [StJudeWasHere/seonaut#6]
**Is your feature request related to a problem? Please describe.**
I want to be sure that the build I'm going to distribute passes an SEO audit, but now it has to be manual. I need to deploy the code and, after deploying, run the audit.

**Describe the solution you'd like**
Add integration to GitHub Action to act as a checker. Code cannot be deployed if the PR generates any critical issues.

**Comment by StJudeWasHere** [comment]
I'm closing this issue as more unit tests have been added and there are no plans to add functional tests at this point. However, I'll be happy to review any pull requests that add more tests.
