### ISSUE TITLE
Docker config: publishing DB port to the host

### ISSUE THREAD

**Issue by klaus-aunds** [StJudeWasHere/seonaut#8]
**Is your feature request related to a problem? Please describe.**
The Docker config publishes the database port to the host in the standard mysqld port. This can (as in my case) conflict with an already running mysqld and prevent the container from starting. I commented out the published ports in the docker config, which seems to have no effect on the running seonaut instance later.

**Describe the solution you'd like**
If there's no need to expose the DB to the host: remove the port publishing for the DB.
If the DB needs to be exposed to the host: use a port other than `3306` on the host. 

**Describe alternatives you've considered**

**Additional context**

**Comment by StJudeWasHere** [comment]
I changed the docker file in ea43e63  so it does not expose the mysql and redis ports to the host by default.

There's also a new docker-compose.dev file which will expose the ports, as I find it useful in some cases. Also, it is now possible to set the port numbers via env variables, which will make it easier to change.
